const p=new URLSearchParams(location.search),slug=(p.get('event')||'demo').trim().slice(0,80),guest=(p.get('to')||'Tamu Undangan').trim().slice(0,80);
const $=id=>document.getElementById(id);$('guestName').textContent=guest;$('commentName').value=guest;
$('openInvitation').addEventListener('click',()=>{$('content').classList.remove('hidden');$('content').scrollIntoView({behavior:'smooth'})});
function text(id,v,f=''){if($(id))$(id).textContent=v||f}
function prettyDate(v){if(!v)return'-';const [y,m,d]=v.split('-').map(Number);return new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(Date.UTC(y,m-1,d)))}
function startCountdown(ds,ts){if(!/^\d{4}-\d{2}-\d{2}$/.test(ds||'')){text('countdownStatus','Tanggal acara belum ditentukan.');return}const [y,m,d]=ds.split('-').map(Number),[h,min]=String(ts||'00:00').split(':').map(Number),target=Date.UTC(y,m-1,d,h-8,min||0);const tick=()=>{let diff=target-Date.now();if(diff<=0){['days','hours','minutes','seconds'].forEach(id=>text(id,'00'));text('countdownStatus','The day is here ✨');clearInterval(timer);return}let s=Math.floor(diff/1000);text('days',String(Math.floor(s/86400)).padStart(2,'0'));text('hours',String(Math.floor(s%86400/3600)).padStart(2,'0'));text('minutes',String(Math.floor(s%3600/60)).padStart(2,'0'));text('seconds',String(s%60).padStart(2,'0'))};tick();const timer=setInterval(tick,1000)}
function gallery(items){const wrap=$('gallery');wrap.replaceChildren();const valid=Array.isArray(items)?items.filter(Boolean):[];if(!valid.length)return;$('gallerySection').classList.remove('hidden');valid.forEach(url=>{const img=document.createElement('img');img.src=url;img.loading='lazy';img.alt='Foto Sweet Seventeen';wrap.appendChild(img)});$('closingImage').src=valid[valid.length-1];$('closingImage').style.display='block'}
async function loadEvent(){try{const r=await fetch('/api/events?slug='+encodeURIComponent(slug)),d=await r.json();if(!r.ok)throw new Error(d.error||'Acara tidak ditemukan');const e=d.event;document.title=(e.event_title||'Sweet Seventeen')+' — Invitation';text('eventLabel',e.event_label,'Sweet Seventeen');text('eventTitle',e.event_title,'Sweet Seventeen');text('mainName',e.main_name,e.event_title);text('closingName',e.main_name,e.event_title);text('subtitle',e.subtitle);text('description',e.description);text('eventDate',prettyDate(e.event_date));text('eventTime',e.event_time?e.event_time+' WITA':'-');text('eventLocation',e.location,'-');if(e.cover_url){$('coverImage').src=e.cover_url;$('coverImage').style.display='block';$('closingImage').src=e.cover_url;$('closingImage').style.display='block'}gallery(e.gallery_urls||[]);startCountdown(e.event_date,e.event_time)}catch(err){text('mainName','Acara belum ditemukan');text('countdownStatus',err.message)}}
function renderComments(items){const w=$('comments');w.replaceChildren();text('commentCount',items.length+' ucapan');if(!items.length){w.textContent='Belum ada ucapan. Jadi yang pertama!';return}items.forEach(i=>{const d=document.createElement('div');d.className='comment';const n=document.createElement('strong');n.textContent=i.guest_name;const m=document.createElement('div');m.textContent=i.message;const t=document.createElement('time');t.textContent=new Date(String(i.created_at).replace(' ','T')+'Z').toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'});d.append(n,m,t);w.appendChild(d)})}
async function loadComments(){try{const r=await fetch('/api/comments?wedding_id='+encodeURIComponent(slug)),d=await r.json();if(!r.ok)throw 0;renderComments(d.comments||[])}catch{$('comments').textContent='Komentar belum dapat dimuat.'}}
$('commentForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('commentName').value.trim(),message=$('commentMessage').value.trim();if(!name||!message)return;text('formStatus','Mengirim...');try{const r=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wedding_id:slug,guest_name:name,message})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Gagal mengirim');$('commentMessage').value='';text('formStatus','Ucapan berhasil dikirim.');loadComments()}catch(err){text('formStatus',err.message)}});
loadEvent();loadComments();